services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myshoppingapp
      - MYSQL_DATABASE=tienda
    ports:
      - "3307:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "4000:4000"
